export const INTRADAY_REPO_ABI = [{
  "type": "constructor",
  "inputs": [{
    "name": "_admin",
    "type": "address",
    "internalType": "address",
  }],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "acceptOffer",
  "inputs": [{
    "name": "_offerId",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "admin",
  "inputs": [],
  "outputs": [{
    "name": "",
    "type": "address",
    "internalType": "address",
  }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "calculateRepaymentAmount",
  "inputs": [{
    "name": "_offerId",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [{
    "name": "totalAmount",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "cancelOffer",
  "inputs": [{
    "name": "_offerId",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "claimCollateral",
  "inputs": [{
    "name": "_offerId",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "createOffer",
  "inputs": [{
    "name": "_lendToken",
    "type": "address",
    "internalType": "address",
  }, {
    "name": "_lendAmount",
    "type": "uint256",
    "internalType": "uint256",
  }, {
    "name": "_collateralToken",
    "type": "address",
    "internalType": "address",
  }, {
    "name": "_collateralAmount",
    "type": "uint256",
    "internalType": "uint256",
  }, {
    "name": "_duration",
    "type": "uint256",
    "internalType": "uint256",
  }, {
    "name": "_lenderFee",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [{
    "name": "offerId",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "getBorrowerOffers",
  "inputs": [{
    "name": "_user",
    "type": "address",
    "internalType": "address",
  }],
  "outputs": [{
    "name": "",
    "type": "tuple[]",
    "internalType": "struct RepoContract.RepoOffer[]",
    "components": [{
      "name": "offerId",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "lender",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "borrower",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "lendToken",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "lendAmount",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "collateralToken",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "collateralAmount",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "duration",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "startTime",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "endTime",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "lenderFee",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "status",
      "type": "uint8",
      "internalType": "enum RepoContract.OfferStatus",
    }],
  }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "getLenderOffers",
  "inputs": [{
    "name": "_user",
    "type": "address",
    "internalType": "address",
  }],
  "outputs": [{
    "name": "",
    "type": "tuple[]",
    "internalType": "struct RepoContract.RepoOffer[]",
    "components": [{
      "name": "offerId",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "lender",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "borrower",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "lendToken",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "lendAmount",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "collateralToken",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "collateralAmount",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "duration",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "startTime",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "endTime",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "lenderFee",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "status",
      "type": "uint8",
      "internalType": "enum RepoContract.OfferStatus",
    }],
  }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "getOpenOffers",
  "inputs": [],
  "outputs": [{
    "name": "",
    "type": "tuple[]",
    "internalType": "struct RepoContract.RepoOffer[]",
    "components": [{
      "name": "offerId",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "lender",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "borrower",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "lendToken",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "lendAmount",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "collateralToken",
      "type": "address",
      "internalType": "address",
    }, {
      "name": "collateralAmount",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "duration",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "startTime",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "endTime",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "lenderFee",
      "type": "uint256",
      "internalType": "uint256",
    }, {
      "name": "status",
      "type": "uint8",
      "internalType": "enum RepoContract.OfferStatus",
    }],
  }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "gracePeriod",
  "inputs": [],
  "outputs": [{
    "name": "",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "offerCounter",
  "inputs": [],
  "outputs": [{
    "name": "",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "offers",
  "inputs": [{
    "name": "",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [{
    "name": "offerId",
    "type": "uint256",
    "internalType": "uint256",
  }, {
    "name": "lender",
    "type": "address",
    "internalType": "address",
  }, {
    "name": "borrower",
    "type": "address",
    "internalType": "address",
  }, {
    "name": "lendToken",
    "type": "address",
    "internalType": "address",
  }, {
    "name": "lendAmount",
    "type": "uint256",
    "internalType": "uint256",
  }, {
    "name": "collateralToken",
    "type": "address",
    "internalType": "address",
  }, {
    "name": "collateralAmount",
    "type": "uint256",
    "internalType": "uint256",
  }, {
    "name": "duration",
    "type": "uint256",
    "internalType": "uint256",
  }, {
    "name": "startTime",
    "type": "uint256",
    "internalType": "uint256",
  }, {
    "name": "endTime",
    "type": "uint256",
    "internalType": "uint256",
  }, {
    "name": "lenderFee",
    "type": "uint256",
    "internalType": "uint256",
  }, {
    "name": "status",
    "type": "uint8",
    "internalType": "enum RepoContract.OfferStatus",
  }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "repayLoan",
  "inputs": [{
    "name": "_offerId",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "setAdmin",
  "inputs": [{
    "name": "_newAdmin",
    "type": "address",
    "internalType": "address",
  }],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "setGracePeriod",
  "inputs": [{
    "name": "_gracePeriod",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [],
  "stateMutability": "nonpayable",
}, {
  "type": "function",
  "name": "userBorrowerOffers",
  "inputs": [{
    "name": "",
    "type": "address",
    "internalType": "address",
  }, {
    "name": "",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [{
    "name": "",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "stateMutability": "view",
}, {
  "type": "function",
  "name": "userLenderOffers",
  "inputs": [{
    "name": "",
    "type": "address",
    "internalType": "address",
  }, {
    "name": "",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "outputs": [{
    "name": "",
    "type": "uint256",
    "internalType": "uint256",
  }],
  "stateMutability": "view",
}, {
  "type": "event",
  "name": "AdminChanged",
  "inputs": [{
    "name": "oldAdmin",
    "type": "address",
    "indexed": true,
    "internalType": "address",
  }, {
    "name": "newAdmin",
    "type": "address",
    "indexed": true,
    "internalType": "address",
  }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "CollateralClaimed",
  "inputs": [{
    "name": "offerId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256",
  }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "CollateralReleased",
  "inputs": [{
    "name": "offerId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256",
  }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "GracePeriodUpdated",
  "inputs": [{
    "name": "newGracePeriod",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256",
  }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "LoanRepaid",
  "inputs": [{
    "name": "offerId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256",
  }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "OfferAccepted",
  "inputs": [{
    "name": "offerId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256",
  }, {
    "name": "borrower",
    "type": "address",
    "indexed": true,
    "internalType": "address",
  }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "OfferCancelled",
  "inputs": [{
    "name": "offerId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256",
  }],
  "anonymous": false,
}, {
  "type": "event",
  "name": "OfferCreated",
  "inputs": [{
    "name": "offerId",
    "type": "uint256",
    "indexed": true,
    "internalType": "uint256",
  }, {
    "name": "lender",
    "type": "address",
    "indexed": true,
    "internalType": "address",
  }],
  "anonymous": false,
}] as const;